### ISSUE TITLE
Validate using YAML string instead of file?

### ISSUE THREAD

**Issue by babakness** [hanami/validations#108]
Hello, is it possible to use a YAML string instead of a file? We want to store YAML by other means than file storage.

Thanks.

**Comment by cllns** [comment]
@babakness If you use the `i18n` gem, which `hanami-validations` supports, you should be able to do this. https://github.com/hanami/validations#internationalization-i18n By default that gem uses YAML files, but it's extensible.

**Comment by joneslee85** [comment]
@babakness thanks for the question. Like @cllns has answered in the last comment, this gem wraps the `dry-validation`, if you want to use different backend, you could set to use `i18n` (please see http://dry-rb.org/gems/dry-validation/error-messages/) and write your own extension backend for `i18n`

**Comment by jodosha** [comment]
@babakness YAML isn't practical for lookup. Indeed all the libraries use this format because it's convenient to store data in a file, but at the startup, a library parses that YAML payload into a Ruby Hash (which is better for lookup).
