### ISSUE TITLE
custom predicates do not work in conjunction with schema

### ISSUE THREAD

**Issue by kaikuchn** [hanami/validations#123]
Greetings,

I've been tinkering with the validations gem since I've been looking for a way to get custom predicates to work with `Hanami::Action::Params` ([see the corresponding issue](https://github.com/hanami/controller/issues/209)).
When I thought I had found a solution it instead blew up in my face saying `NoMethodError: undefined method 'messages' for #<Dry::Validation::Messages::YAML:0x007fec9b10cfb8>`. Don't worry, I'm unharmed :grin:

However, I do believe I may have discovered a bug in the Wrapper around the dry-validation gem.
I have managed to construct a small example to reproduce this:
```ruby
require 'hanami/validations'

class Signup
  include Hanami::Validations
  
  predicate(:boom?, message: 'boom!') { |bomb| bomb.nil? }
  validations do
    required(:bomb_site).schema do
      required(:bomb) { boom? }
    end
  end
end
```

When you do not use `schema` it works as expected. So this is only a problem when one wants to use a custom predicate in conjunction with nested input data.

Best regards,
Kai

**Comment by jodosha** [comment]
@kaikuchn 

> Don't worry, I'm unharmed

😂  Glad to head that!

---

This was already fixed with #122. If you try with the `HEAD` of `master` branch it will work as expected.
