### ISSUE TITLE
Controller doesn't pay attention to `validate` block

### ISSUE THREAD

**Issue by jarosluv** [hanami/validations#130]
Hanami doesn't pay attention to [validate block](http://dry-rb.org/gems/dry-validation/custom-validation-blocks/) during controller params validation.

Please, see gist special for this case https://gist.github.com/jarosluv/947d6d30f85554681eb3d1ee9c8e22cd

Note: Block `validate` returns `false`, but Hanami believes  that there are no errors. This matters only in controller params validation.

**Comment by mereghost** [comment]
@jarosluv Hmmm... It seems that your validation schema isn't doing what you expect:

```
> FooSchema.call({ foo: { title: 'OK' } })
#<Dry::Validation::Result output={:foo=>{:title=>"OK"}} errors={}>
```

**Comment by jarosluv** [comment]
@davydovanton @mereghost 

Guys, I'm so sorry. It seems that this is really my bad. I mess around with `validate` for the last few days and totally confused.

I forgot about `required(:title).filled` in my gist. But the real mistake is using `message: "Foo is wtf?!"` as `validate` params. I've been suffered with [this issue](https://github.com/hanami/validations/issues/129) for so long that I decided that we can use `message` params like in `predicate` block. But not. It just suppress the `validate` block and nothing else.

I still can't get it to work on my production app and I can't  reproduce the problem in my current gist. I think all problems starts [here](https://github.com/hanami/validations/issues/129). May be we will try to solve it?

**Comment by AlfonsoUceda** [comment]
@jarosluv I'm going to close this issue and focus in the issue you opened in `hanami-validations`
