### ISSUE TITLE
[Question] Validation Object receiving key arguments as string or symbol

### ISSUE THREAD

**Issue by AlexanderMint** [hanami/validations#133]
How to make so there would be no mistake if type key = string or symbol?

``` ruby
require 'hanami-validations'
class Signup
  include Hanami::Validations

  validations do
    required(:name) { filled? }
  end
end

Signup.new('name' => 'Luca').validate.errors # Error: {:name=>["is missing"]}
Signup.new(name: 'Luca').validate.errors # {}
```

There is a bad decision
``` ruby
module Hanami
  module Validations
    require 'json'

    def initialize(input = {})
      @input = JSON.parse(JSON[input.to_h], symbolize_names: true)
    end
  end
end

Signup.new('name' => 'Luca').validate.errors # {}
Signup.new(name: 'Luca').validate.errors # {}
```

**Comment by AlfonsoUceda** [comment]
@AlexanderMint thanks for this issue, I'll take a look ;)

**Comment by AlfonsoUceda** [comment]
@AlexanderMint it seems a problem in `dry-validation` gem, do you need convert keys in symbols? you can take a look to `Hanami::Utils::Hash`

**Comment by AlfonsoUceda** [comment]
If you need the reference https://github.com/dry-rb/dry-validation/issues/333

**Comment by AlfonsoUceda** [comment]
Closing this issue because it was resolved for now. As a workaround, define the schema with strings an use strings or define it with symbols and use symbols.
