### ISSUE TITLE
Make validations a callable object

### ISSUE THREAD

**Issue by gizotti** [hanami/validations#134]
At his talk at railsclub(https://www.youtube.com/watch?v=SRQVhHzW-Eo) @jodosha talked about 
 making changes to `Hanami::Validations` to make it a callable object.

I am happy to start working on this, would just like some guidance so I can move in the right direction.

Would we have to make this backwards compatible still allowing for params to be set on initialization?

I would also like to work on moving it from being a `Mixin` to being an "inheritable" class as also mentioned in the talk, but that would be a separate Issue/PR.

**Comment by jodosha** [comment]
> Would we have to make this backwards compatible still allowing for params to be set on initialization?

Nope. Params must be arguments of `#call`.

**Comment by jodosha** [comment]
Implemented by #180
