### ISSUE TITLE
Fail on incomplete expression?

### ISSUE THREAD

**Issue by malin-as** [hanami/validations#135]
In order to check for a field to be always be present, but with any possible value (including `nil`), please check the following example:
```ruby
require 'hanami-validations'

class Test
  include Hanami::Validations

  validations do
    required(:present)
    required(:present2).maybe
  end
end

p Test.new.validate
```
It returns:
```ruby
<Dry::Validation::Result output={} errors={:present2=>["is missing"]}>
```

Either `required(:present)` is an incomplete expression, in which case Hanami should not silently ignore it, or it is equivalent to `required(:present).maybe`, in which case it should display the same behaviour.

**Comment by jodosha** [comment]
@malin-as Thanks for bringing this discussion. I'm not sure if that is possible at the moment, and I'm afraid it would be a breaking change.

@solnic @flash-gordon any opinion on this?
