### ISSUE TITLE
+key?+ is not a valid predicate name

### ISSUE THREAD

**Issue by wizardone** [hanami/validations#142]
Hey *,

I get the following error when trying to validate with a Custom predicate module, that is called just `Predicates`, e.g.

```ruby
module Predicates
  include Hanami::Validations::Predicates

  self.messages_path = File.expand_path('../errors.yml', __FILE__)

  predicate :email? do |value|
    !/\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i.match(value).nil?
  end
end
```

```ruby
require_relative 'predicates'
class BaseSchema
  include Hanami::Validations
  predicates Predicates
end
```
The resulting error when calling `.validate` is:
```
ArgumentError +key?+ is not a valid predicate name
```
Obviously if I rename the module to `CustomPredicates` or anything else it works, but just wanted to mention it to you (it took me some time to figure it out, although it makes good sense). Maybe it can be addressed in the README, so other fellow idiots like me won't stumble upon this problem 😃 
Cheers!

**Comment by jodosha** [comment]
@wizardone By using `Predicates` you're referring to `Hanami::Validations::Predicates`. You should pick a different name, or use `::Predicates`.
