### ISSUE TITLE
dry-validation val() doesn't work for predicates

### ISSUE THREAD

**Issue by greggilbert** [hanami/validations#155]
I might be going about this the wrong way, but suppose I want to create a predicate that checks to see if a subdomain is already taken. I want it to pass if the value passed in is already in use by the object.

So for example, given this input:
```
{ id: 3, subdomain: 'foo' }
```

If you were editing id=3 and you tried to save using the value 'foo', it would pass because it's already being used. Compare to id=5, where it should fail since it's not id=3.

Here's my predicate:

```
    predicate :unused_subdomain?, message: 'This subdomain is already taken.' do |current|

      host = ::Host.where(subdomain: current['subdomain'])
      return true if host.nil?
      
      if current.key?('id')
        if current['id'] == host.id
          return true
        end
      end
      
      false
    end

    validations do
      required(:subdomain) { filled? & unused_subdomain?(:id) }
    end
```

dry-validation has a `val()` function, so in a schema you can do something like `unused_subdomain?(val(:id))` and it should work. Is there an equivalent in Hanami? Or is there a better way to pull this off?

**Comment by jodosha** [comment]
Closing as stale conversation.
