### ISSUE TITLE
Support for preprocessing?

### ISSUE THREAD

**Issue by jswanner** [hanami/validations#156]
Thanks for the great framework.

I've been trying, without success, to figure out how to make dry-validation's [input preprocessing]( https://dry-rb.org/gems/dry-validation/input-preprocessing/) work. Is this possible?

I'm also using this in the context of an action's params, so perhaps this issue is better suited to https://github.com/hanami/controller instead.

**Comment by jodosha** [comment]
@jswanner Here's how to do:

```ruby
# frozen_string_literal: true

require "bundler/setup"
require "hanami/validations"
require "hanami/validations/form"
require "hanami/controller"

module Types
  include Dry::Types.module

  Name = Types::String.constructor do |str|
    str ? str.strip.chomp : str
  end
end

class PropertyValidator
  include Hanami::Validations::Form

  validations do
    configure do
      config.type_specs = true
    end

    required(:name, Types::Name).filled(min_size?: 1)
  end
end

params = { "name" => "\t François \n" }
result = PropertyValidator.new(params).validate
puts result.success?
puts result[:name]

class MyAction
  include Hanami::Action

  params do
    configure do
      config.type_specs = true
    end

    required(:name, Types::Name).filled(min_size?: 1)
  end

  def call(params)
    if params.valid?
      puts "yes"
      puts params[:name]
    else
      puts "nope"
    end
  end
end

MyAction.new.call(params)
```

```shell
$ ruby test.rb
true
François
yes
François
```

---

Please be aware that [input preprocessing](https://dry-rb.org/gems/dry-validation/0.13/input-preprocessing/) has been removed from `dry-validation`. In 1.0 you can used directly custom types: see https://dry-rb.org/gems/dry-validation/1.0/schemas/ (**Using custom types** section).
