### ISSUE TITLE
Add a simple a helper method to shorten validate.success? with valid? [Law of Demeter]

### ISSUE THREAD

**Issue by azbshiri** [hanami/validations#157]
```
+    # A simple a helper method to shorten validate.success?
+    #
+    # @return [Boolean]
+    #
+    # @since 0.2.4
+    def valid?
+      validate.success?
+    end
```

I think it's easier to just call `valid?` on a form variable like below:
```
form = SurveyForm.new({})
if form.valid?
  # do something
else
  # return errors
end
```
instead of 

```
form = SurveyForm.new({})
if form.validate.success? # Breaks Law of Demeter
  # do something
else
  # return errors
end
```

**Comment by jodosha** [comment]
@azbshiri Thanks for the suggestion, but I don't believe this is a good idea, given the different direction we're taking with 2.0. I want to avoid to form new habits that will disappear soon.

In 2.0 data will be passed as argument to `#call`:

```ruby
form = SurveyForm.new
result = form.call({})

if result.success?
  # ...
else
  # ...
end
```

It this way there is no longer need for this short circuit you're suggesting.
