### ISSUE TITLE
Nested Validations Not Working

### ISSUE THREAD

**Issue by nomanurrehman** [hanami/validations#159]
I am posting the following JSON.

```
{
  "user":{
    "first_name": "Noman",
    "last_name": "Rehman",
    "email": "noman@rehman.com"
  }
}
```

From what I understand, this is what I should have in my controller to let this go through.

```
params do
  required(:user).schema do
    required(:first_name)
    required(:last_name)
    required(:email)
  end
end
```

However, this does not work and I am getting `{"user": {}}` as a result of `params.to_h`.

However, the following combinations work and I am getting the complete user object when I call `params.to_h`.

```
params do
  required(:first_name)
  required(:last_name)
  required(:email)
end
```
```
params do
  required(:user)
end
```

**Comment by cllns** [comment]
Can you try addling `.filled` (or `.maybe`) to the predicate lines?

So:
```ruby
params do
  required(:user).schema do
    required(:first_name).filled
    required(:last_name).filled
    required(:email).filled
  end
end
```

I think that should fix this issue. Please close this issue if so :)

**Comment by jodosha** [comment]
@nomanurrehman I'm closing it for now, as @cllns suggestion is correct. Please let us to know if it still doesn't work.
