### ISSUE TITLE
Updating dry-validation ?

### ISSUE THREAD

**Issue by unhappychoice** [hanami/validations#202]
`dry-validation` already has many releases and `hanami-validations` depends on 0.11.x for a long time.
So do we need updating dry-validation ?

# Updating to 1.5.1 ( Latest )
I don't know exact,  but `hanami-validations` might need to have lots of breaking changes.
But it seems to be many useful features.

Ref: https://github.com/dry-rb/dry-validation/blob/master/CHANGELOG.md#151-2020-06-18

# Updating to 0.13.0 ( Latest minor version )
There is a breaking change, but `hanami-validations` may handle that without any breaking changes.

> [BREAKING] Form was renamed to Params to be consistent with the latest changes from dry-types. You can require 'dry/validation/compat/form' to use the previous names but it will be removed in the next version (flash-gordon)

Ref: https://github.com/dry-rb/dry-validation/blob/master/CHANGELOG.md#0120-2018-05-31

**Comment by jodosha** [comment]
@unhappychoice Did you try with this version? https://rubygems.org/gems/hanami-validations/versions/2.0.0.alpha1

**Comment by unhappychoice** [comment]
Ah, sorry, I just couldn't find the version and branches, thanks :pray:

**Comment by jodosha** [comment]
@unhappychoice No worries. FYI - https://github.com/hanami/controller/blob/master/CHANGELOG.md#v133---2020-01-14
