### ISSUE TITLE
Custom validation plugin API

### ISSUE THREAD

**Issue by ianks** [hanami/validations#72]
Firstly I would like to say that I *love* Lotus validations. I have actually almost entirely replaced my ActiveModel validations with it, and it has been a dream to work with.

Since I use Lotus separately from the rest of the Lotus framework, there is one feature I really would love to have: the ability to create custom validations. Looking in the source, there are a finite number of accepted validation types in the API, specifically:

```ruby
      VALIDATIONS = [
        :presence,
        :acceptance,
        :format,
        :inclusion,
        :exclusion,
        :confirmation,
        :size,
        :type,
        :nested
      ].freeze
```

I would like to be able to create my own validations, and append to this list. For example, say I wanted to validate the authenticity of a token, it would nice to be able to create my own validator for this:

```ruby
attribute :jwt_token, authenticity: true
```

This would allow me to create my own logic to verify the authenticity of a token, and have it validated by Lotus.

Currently, to achieve this, I can do some somewhat nasty monkey-patching by overriding `#valid?`

```ruby
def valid?
  super()
  validate_jwt_token_authenticity
  errors.empty?
end

def validate_jwt_token_authenticity
  if external_jwt_validation
    errors.add :jwt_token, Lotus::Validations::Error.new(:jwt_token, :presence, true, false)
  end
end
```

Would you guys accept a PR which created a way in which users could add custom validations to the validation set? I would like to add this functionality if possible :smile: 

Thoughts? Concerns? Would love to hear what you guys think about this!

- Ian

**Comment by jodosha** [comment]
@ianks Hello and thanks for sparking this discussion. This is something that we want to do for sure before 1.0.

We didn't found an elegant/convenient way to describe custom validations, but we look for new ideas. Would you love to contribute on the brainstorming? Eg. how do you imagine the API? Thanks! :+1: 

/cc @lotus/core-team

**Comment by solnic** [comment]
FWIW here's how you can do it in dry-validation already and it doesn't require any special API:

``` ruby
schema = Dry::Validation.Schema do
  configure do
    def is_it_awesome?(value)
      value == 'awesome'
    end
  end

  key(:text).required(:str?, :is_it_awesome?)
end
```

Notice that you compose custom predicates with built-in ones, so you can leverage that easily w/o any special code.
