### ISSUE TITLE
PORO validator

### ISSUE THREAD

**Issue by magicalbanana** [hanami/validations#79]
This would be a feature request but would be nice if we could implement this to be just a PORO validator as well.

Perhaps do something like Virtus where you can set the constructor or the mass assignments.

**Comment by jodosha** [comment]
@magicalbanana Hey, can you please tell us more about your idea? Thank you!

**Comment by magicalbanana** [comment]
@jodosha take a look at [Virtus](https://github.com/magicalbanana/veto) it's a good PORO validator really and I like the idea that the validation is handled outside or is of a seperate concern.

Because (correct me if I am wrong) but the idea of Lotus is to make it modular right? So the validations should not create the attributes but rather just validate the attribute when passed an entity. Because I think right now it's like an Entity with a built-in validator right?

[Virtus](https://github.com/solnic/virtus) has some configs you can pass when including the module.

(Cherry-picking extensions)[https://github.com/solnic/virtus#cherry-picking-extensions]

If we had something like this for the validator it would be kewl because it would make our code readable. We would have attributes defined and state the validations we're going to be using.

I hope this makes sense. I can help making this a feature but would like to have a code walk prior to starting (it's just easier for me to get the run down of the code from the original coder).

**Comment by deepj** [comment]
And what `Lotus::Validations` replace by [Dry::Validation](https://github.com/dryrb/dry-validation)?

I see here a good fit with philosophy of Lotus. And it can be used more widely such as forms, params and so on...

**Comment by magicalbanana** [comment]
Also, I've am in the process of making mine as well [PoroValidator](https://github.com/magicalbanana/poro_validator)

If you guys could give feedback that would be great. It's still WIP but the core classes are already there, I am just now making the validations.

**Comment by jodosha** [comment]
@deepj Starting from next week, I'll explore Dry::Validation for that purpose :+1:

**Comment by solnic** [comment]
Thanks for suggesting dry-validation. We'll be looking into how it can help Lotus. One thing I should mention is that dry-validation is for validating *data*, for now we only support objects responding to `[]` but next version will support validating objects through attr readers, too. Personally I don't think it's gonna be a common thing to do, but since it is simple to support, we're gonna add that.

**Comment by jodosha** [comment]
@solnic Thank you :+1:

**Comment by jodosha** [comment]
Closed by #100
